FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
COPY . .

RUN yarn install && yarn run build

FROM node:18-alpine as production

RUN npm install -g serve

WORKDIR /app

COPY --from=build  /app/dist ./dist/

EXPOSE 3000

CMD serve -s dist

